name = "MacroUtilities"
uuid = "274a0f0b-05f4-4024-87ff-de4a5b524b4f"
authors = ["Curt Da Silva <curt.dasilva@gmail.com>"]
version = "1.7.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Tricks = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"

[compat]
MLStyle = "0.4.17"
OrderedCollections = "1"
Tricks = "0.1.7"
julia = "1.6"
